version: "3.8"

services:
  portfolio-frontend:
    build:
      context: ./frontend
    container_name: portfolio-frontend
    command: yarn dev --host 0.0.0.0 --port 5173
    ports:
      - "5175:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - portfolio-api

  portfolio-api:
    build:
      context: ./backend
    container_name: portfolio-api
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8007
      "
    ports:
      - "8007:8007"
    volumes:
      - ./backend:/api
